### ISSUE TITLE
Convert the R documents from Rmarkdown to Quarto

### ISSUE THREAD

**Issue by antagomir** [fennicahub/fennica#5]
Quarto makes it possible to build books (to my understanding without any additional packages), should be relatively straightforward to migrate from Rmarkdown: https://bookdown.org/aepstk/min-quarto/

However please check it works before changing everything..

**Comment by pitkant** [comment]
Looking at the new version of the website I noticed the following issues:
- [Chapter 10](http://fennica-fennica.rahtiapp.fi/publisher.html) is called "publisher field" in the table of contents. This seems to be due to the code comment in the first R code chunk:

```{r source-publisher, include=FALSE, eval=knit_bookdown}
# publisher field
source("publisher.R")
```

- In [Chapter 13](http://fennica-fennica.rahtiapp.fi/publication_time.html) the title of the chapter is listed as "Publication place field and derived country- and geoinformation", which is the same as in chapter 12. Chapter 13 is actually "Publication year summaries". In addition to the title being wrong, the title in the opened chapter page is a bit too long. If I remember correctly it was not "Publication place field and derived country- and geoinformation" in the RMD files but maybe something short such as "Publication time".
- The first page [index.qmd](https://github.com/fennicahub/fennica/blob/master/inst/examples/index.qmd) is unique in the sense that it has metadata in the front matter.

- [ ] All .qmd documents should be looked through and explicit front matter added to them. Nothing fancy like in index.qmd, a title field with a short and descriptive name is sufficient.

**Comment by ake123** [comment]
@ElliotvGP Can you look into this and fix the issue?

**Comment by ElliotvGP** [comment]
Do you have an example of what title or description I should add to the files? Technically it's not difficult to add a title or a description but I don't really know what to write.

**Comment by pitkant** [comment]
> Do you have an example of what title or description I should add to the files? Technically it's not difficult to add a title or a description but I don't really know what to write.

In my opinion the title can be the same as the text on the first content row of the document (1st (`#`) or 2nd (`##`) heading level). In some cases the heading in the text was not the same as in the front matter but in this case it's ok if you just copy-paste the first heading text to front matter.

An example of front-matter and heading mismatch:

```
---
title: "Language summaries"
author: "Leo Lahti"
date: "`r Sys.Date()`"
output: markdown_document
---

## Language
[...]
```

but it would be ok if it's just

```
---
title: "Language"
---
```

from now on. We will probably have to do one final check before the end of this project to see that the titles are understandable. (e.g. "Holder" is a bit cryptic)

**Comment by ElliotvGP** [comment]
thanks !

**Comment by pitkant** [comment]
By experimenting with titles, I mean this:

<img width="1419" alt="Näyttökuva 2023-6-26 kello 16 10 03" src="https://github.com/fennicahub/fennica/assets/69813611/24e13022-b50f-4ef2-a6b8-8e93db48c85e">
Is the front-matter title always used in the left-side TOC? Is the right-side TOC only active when there are headings in the text? Would the front-matter title get an ordinal number before it it was the only title, with no headings in the file? What if the heading was a 2nd level heading?

<img width="1343" alt="Näyttökuva 2023-6-26 kello 16 10 10" src="https://github.com/fennicahub/fennica/assets/69813611/91876830-f767-4bc6-827d-ebcdaf2976d7">
On the other hand there is no right-side TOC in Author's lifetime.

**Comment by ElliotvGP** [comment]
I think because author's lifetime doesn't have a subtitle, it can't have a TOC

**Comment by antagomir** [comment]
That would be fine.

**Comment by antagomir** [comment]
Is this one ready?

**Comment by ake123** [comment]
This is ready!
